TRAIN:
  # ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 32
  EVAL_PERIOD: 2
  # CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: caffe2
  # AUTO_RESUME: True
  FINETUNE: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  # TRAIN_JITTER_SCALES: [256, 320]
  # TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  # INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  FRAME_SAMPLING: 'like omnivore'
SLOWFAST:
  ALPHA: 4
  # BETA_INV: 8
  # FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  # WIDTH_PER_GROUP: 64
  # NUM_GROUPS: 1
  # DEPTH: 50
  # TRANS_FUNC: bottleneck_transform
  # STRIDE_1X1: False
  # NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  # SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  # SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  # GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  # INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  # NUM_BATCHES_PRECISE: 200
  # MOMENTUM: 0.1
  # WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  # MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.001
  # OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: omnivore_swinB_epic
  MODEL_NAME: Omnivore
  # LOSS_FUNC: cross_entropy
  # DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 2
  # NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 1
# DATA_LOADER:
#   NUM_WORKERS: 8
#   PIN_MEMORY: True
# EPICKITCHENS:
#   TRAIN_PLUS_VAL: False
# NUM_GPUS: 8     # ✓✓✓✓✓✓
# NUM_SHARDS: 1   # ✓✓✓✓✓✓
NUM_GPUS: 1     # ✓✓✓✓✓✓
OUTPUT_DIR: output   # ✓✓✓✓✓✓
